var MAX_MESSAGE_SIZE = 1088
var MINIMAL_PADDING = 16
var HEADER_SIZE = 48
var MESSAGE_BODY = MAX_MESSAGE_SIZE - HEADER_SIZE - MINIMAL_PADDING

var MAX_OUTGOING = 128
var MAX_INCOMING = 64

var MAXIMUM_UNPROCESSED_SEND_BYTES = 1024 * 1024

var MILLISECOND = 1000000
var SECOND = MILLISECOND * 1000

var MAX_SECONDS_IN_DURATION = (Number.MAX_SAFE_INTEGER / SECOND) - 1

module.exports = {
  MAX_MESSAGE_SIZE: MAX_MESSAGE_SIZE,
  MINIMAL_PADDING: MINIMAL_PADDING,
  HEADER_SIZE: HEADER_SIZE,
  MESSAGE_BODY: MESSAGE_BODY,
  MAX_OUTGOING: MAX_OUTGOING,
  MAX_INCOMING: MAX_INCOMING,
  MAXIMUM_UNPROCESSED_SEND_BYTES: MAXIMUM_UNPROCESSED_SEND_BYTES,
  MILLISECOND: MILLISECOND,
  SECOND: SECOND,
  MAX_SECONDS_IN_DURATION: MAX_SECONDS_IN_DURATION
}
